name: cicd pipeline for java maven application

on: push

jobs:
    build_java_maven_app:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'  # REQUIRED input
                java-version: '17'       # REQUIRED input

            - name: Build with maven
              run: mvn clean install

            - name: Run tests
              run: mvn test

